// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4wFhR3wrp-Bcaxu5rFALIJVfBvYhX2U',
    appId: '1:884903744615:web:3b18c57a370cb9548b30c2',
    messagingSenderId: '884903744615',
    projectId: 'chatting-app-a594d',
    authDomain: 'chatting-app-a594d.firebaseapp.com',
    storageBucket: 'chatting-app-a594d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Ufsn_zc413-CfZgvM5u8mwRKXjbeTH8',
    appId: '1:884903744615:android:38b9afa7ae65a1f08b30c2',
    messagingSenderId: '884903744615',
    projectId: 'chatting-app-a594d',
    storageBucket: 'chatting-app-a594d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU6D_QC4ad4N9gTasL2Nmuq2Fp53A0Q7Q',
    appId: '1:884903744615:ios:4d715b43420cbbe28b30c2',
    messagingSenderId: '884903744615',
    projectId: 'chatting-app-a594d',
    storageBucket: 'chatting-app-a594d.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU6D_QC4ad4N9gTasL2Nmuq2Fp53A0Q7Q',
    appId: '1:884903744615:ios:4d715b43420cbbe28b30c2',
    messagingSenderId: '884903744615',
    projectId: 'chatting-app-a594d',
    storageBucket: 'chatting-app-a594d.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu4wFhR3wrp-Bcaxu5rFALIJVfBvYhX2U',
    appId: '1:884903744615:web:264871b4c8ff23e18b30c2',
    messagingSenderId: '884903744615',
    projectId: 'chatting-app-a594d',
    authDomain: 'chatting-app-a594d.firebaseapp.com',
    storageBucket: 'chatting-app-a594d.appspot.com',
  );

}